apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice-web
spec:
  template:
    spec:
      containers:
        - name: alice-web
          image: gcr.io/alice-ws/test/alice-web:0.0.1
          ports:
            - containerPort: 8080