# Golang CircleCI 2.0 configuration file
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.11.0
  cloudrun: circleci/gcp-cloud-run@1.0.2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15
    steps:
      - checkout

      - run: go build -v ./cmd/glaive
      - run: go test -v ./...
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/deploy:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/glaive-api:${CIRCLE_SHA1}'
          platform: managed
          region: us-central1
          service-name: igiari-api
          unauthenticated: true
      - cloudrun/deploy:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/glaive-web:${CIRCLE_SHA1}'
          platform: managed
          region: us-central1
          service-name: igiari-api
          unauthenticated: true

# This is currently unused.
  build-web:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run: node --version
      - run: cd web
      - run: npm install
      - run: npm run build
workflows:
  commit:
    jobs:
      - build
      - gcp-gcr/build-and-push-image:
          #          docker-context: .
          image: glaive-api
          tag: $CIRCLE_SHA1
          requires:
            - build
      - gcp-gcr/build-and-push-image:
          docker-context: ./web/
          workspace-root: ./web/
          dockerfile: ./web/Dockerfile
          image: glaive-web
          tag: $CIRCLE_SHA1
      - deploy:
          requires:
            - build
            - gcp-gcr/build-and-push-image-1
            - gcp-gcr/build-and-push-image-2
          filters:
            branches:
              only:
                - master