# Golang CircleCI 2.0 configuration file
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.11.0
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15
    steps:
      - checkout

      - run: go build -v ./cmd/glaive
      - run: go test -v ./...

# This is currently unused.
  build-web:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run: node --version
      - run: cd web
      - run: npm install
      - run: npm run build
workflows:
  commit:
    jobs:
      - build
      - gcp-gcr/build-and-push-image:
          #          docker-context: .
          image: glaive-api
          tag: $CIRCLE_SHA1
      - gcp-gcr/build-and-push-image:
          docker-context: ./web/
          workspace-root: ./web/
          dockerfile: ./web/Dockerfile
          image: glaive-web
          tag: $CIRCLE_SHA1
