namespace: alice-web-production
commonLabels:
  variant: production
resources:
  - ../base
  - namespace.yaml
  - ingress.yaml
patchesStrategicMerge:
  - deployment_replicas.yaml
  - deployment_spec.yaml