boards:
  /a/:
    URI: https://api.igiari.net/a
    ImageURI: https://storage.googleapis.com/igiari-glv-media
  /c/:
    URI: https://api.igiari.net/c
    ImageURI: https://storage.googleapis.com/igiari-glv-media
  /po/:
    URI: https://api.igiari.net/po
    ImageURI: https://storage.googleapis.com/igiari-glv-media
defaultTime: 1343080585
version: 2
